import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextThemeProvider from "@/providers/theme-provider";
import GlobalState from "@/context";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="dark:bg-black">
        <NextThemeProvider>
          <GlobalState>
            <Header/>
            {children}
          </GlobalState>
        </NextThemeProvider>
      </body>
    </html>
  );
}
